# Generated by Django 3.2 on 2021-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
